# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Debug'
  
stages:
- stage: Develop
  condition: OR(eq(variables['Build.SourceBranch'], 'refs/heads/develop') ,eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/develop'))
  jobs:
  - job: BuildJob
    steps:
    - task: DotNetCoreCLI@2  
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'OpenReferralsUI'
- stage: Master
  condition: OR(eq(variables['Build.SourceBranch'], 'refs/heads/master') ,eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/master'))
  jobs:
  - job: BuildJob
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          rm appsettings.json -f
          mv appsettings.Prod.json appsettings.json
    - task: DotNetCoreCLI@2  
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'OpenReferralsUI'
